[package]
name = "rustitude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = { version = "0.5.1", features = ["num-complex"] }
nalgebra = "0.32.3"
ndarray = "0.15.6"
ndarray-linalg = { version = "0.16.0", features = ["openblas-static"] }
nshare = { version = "0.9.0", features = ["nalgebra", "ndarray"] }
num = "0.4.1"
num-complex = "0.4.4"
polars = { version = "0.34.2", features = ["parquet", "describe"] }
rayon = "1.8.0"
sphrs = "0.2.2"
